# Generated by Django 2.2.6 on 2019-10-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20191012_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refreshRate',
            field=models.TextField(null=True),
        ),
    ]
