# Generated by Django 2.2.6 on 2019-10-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_product_refreshrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='refreshRate',
        ),
    ]
